# Site settings
title: Blog
name: xxppcc # your name
email: chaopeng002@gmail.com # your email address
description: >
    A Simple Jekyll Blog Theme. # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://xxppcc.github.io/" # the base hostname & protocol for your site
twitter_username: # your Twitter username
github_username: xxppcc
disqus_username: # your disqus username

google-analytics: # add it if you have one

skillstree: true # turn on or off the skills tree in about page

# Build settings
permalink: none
markdown: kramdown
